[project]
name = "sea-surface-temp-viz"
version = "0.1.0"
description = "Visualization of earth sea surface temperatures"
requires-python = ">=3.12"
dependencies = [
    "aiohttp==3.10.5",
    "h5py==3.11.0",
    "matplotlib==3.9.0",
    "numpy==2.0.0",
    "requests==2.32.3",
    "urllib3==1.26.19",
]

# Pyright language server: use our .venv
[tool.pyright]
venvPath = "."
venv = ".venv"
